~RS~OL~BK~FW ~RS~FY__+___   ~FM/\/\         ~FWSi v pristave ostrova Portalis, ktory tvori vstupnu branu
~OL~FT/  ~RS~FY|  ~OL~FT/  ~RS~FM\/ \/\        ~FWpre Atlantidanov,  uprednostnujucich prepravu lodami pred
~OL~FT\_~RS~FW/~FY|~FW\~OL~FT_\  ~RS~OL~FWJ   ~RS~FM\./\__    ~FWcestovanim letunmi. Pristav je velkym tranzitnym stredis-
 /~FY_|_~FW\~FY_      ~FM|~FT][_]~FM(    ~FWkom a je to vlastne jedine obyvane miesto na tomto ostro-
 ~FY\/\/\/ ~FW__   ~FM\.~OL~FK/~RS~FM_~OL~FK\~RS~FM./   ~FWve. Nachadzaju  sa tu  velke sklady, zasobujuce Atlantis,
 ~FY( () )  ====~OL~FK/_/ \_\   ~RS~FWako aj niekolko hotelov pre navstevnikov, ktory prisli na
~OL~BB~FW^^^^^^^^^~RS~BB~FY|~OL~BB~FW^~RS~BK~FY(_._._._.   ~FWPortalis za oddychom ci unikom z kazdodenneho zivota...
