Si v hlavnom pristave Atlantidy. Prave z  tohoto miesta sa               ~FY___+__
~FWvydavaju lode do  vsetkych krajin  sveta, za obchodom a za      ~OL~FG/~RS~FG/~FR====~OL~FG\  ~RS~OL~FT\  ~RS~FY|  ~OL~FT\
~RS~FWnovymi  objavmi. Prechadzaju sa tu hordy namornikov a roz-   ~OL~FG/~RS~FG/~FR===~OL~FG\   ~RS~OL~FKJ  ~RS~OL~FT/_~RS~FW/~FY|~FW\~OL~FT_/
~RS~FWpravaju nahodnym posluchacom o svojich stretnutiach s tymi   ~FR|| | ~OL~FKJ      ~RS~FY_~FW/~FY_|_~FW\
najhroznejsimi priserami hlbin.  Stovky lodi tu kazdodenne   ~FR|| |      ~FT__~FY\/\/\/
~FWopusta brehy  Atlantidy, aby z pevniny  dopravili  zasoby,  ~FG/~FR||~FG\ ~OL~FG\~RS~FY-====  ( () )
~FWpotrebne pre kazdodenny zivot obyvatelov Atlantidy...       ~FYX][X][X]~OL~BB~FW^^~RS~BB~FY|~OL~BB~FW^^^^^^^^^
