Nachadzas sa na palube malej vyletnej lode,  ktora vykonava        ~FY___|___
~FWpravidelne  plavby medzi hlavnym mestom Atlantidy a blizkym       ~OL~FT//// ///
~RS~FWostrovom  Portalis, vzdialenom par mil od brehov Atlantisu.      ~OL~FT| || |||
~RS~FWProva lode ladne rozraza spenene vlny mora v rychlej plavbe       ~OL~FT\_\\\_\\ ~RS~FY____
~FWku brehom Atlantisu, ktorej tmave pobrezie sa  zretelne cr- ~FY---\===___|___[~OL~FY###~RS~FY]
~FWta na horizonte. Z casu na cas vidis vo velkej vyske letiet     ~FY(____________(\
~FWletun, spajajuci Portalis s Atlantisom vzdusnym mostom...   ~OL~BB~FW^^^^^^^^^^^^^^^^^^^^
